{$include 'basic_inc.inc.pas'}
{$include 'ch376s_inc.inc.pas'}
{$include 'dram_inc.inc.pas'}
{$include 'fdc_inc.inc.pas'}
{$include 'GABE_Control_Registers_def.inc.pas'}
{$include 'interrupt_def.inc.pas'}
{$include 'io_def.inc.pas'}
{$include 'kernel_inc.inc.pas'}
{$include 'keyboard_def.inc.pas'}
{$include 'Math_def.inc.pas'}
{$include 'Math_Float_def.inc.pas'}
{$include 'monitor_inc.inc.pas'}
{$include 'OPL3_def.inc.pas'}
{$include 'RTC_def.inc.pas'}
{$include 'SDCard_Controller_def.inc.pas'}
{$include 'sdos_fat_vars_fmx_inc.inc.pas'}
{$include 'sdos_fat_vars_user_inc.inc.pas'}
{$include 'SID_def.inc.pas'}
{$include 'super_io_def.inc.pas'}
{$include 'timer_def.inc.pas'}
{$include 'Trinity_CFP9301_def.inc.pas'}
{$include 'Unity_CFP9307_def.inc.pas'}
{$include 'vicky_ii_def.inc.pas'}
{$include 'VKYII_CFP9553_BITMAP_def.inc.pas'}
{$include 'VKYII_CFP9553_COLLISION_def.inc.pas'}
{$include 'VKYII_CFP9553_SDMA_def.inc.pas'}
{$include 'VKYII_CFP9553_SPRITE_def.inc.pas'}
{$include 'VKYII_CFP9553_TILEMAP_def.inc.pas'}
{$include 'VKYII_CFP9553_VDMA_def.inc.pas'}
